version: '3.8'
services:
  postgres:
    image: postgres:13  # Use the version of PostgreSQL you prefer
    platform: linux/arm64/v8
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  users:
    build: ./users-service
    ports:
      - "8100:8000"
    volumes:
      - ./users-service:/app  # Mount the application code into the container
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/usersdb
    depends_on:
      - postgres
      - rabbitmq

  notifications:
    build: ./notifications-service
    ports:
      - "8200:8000"
    volumes:
      - ./notifications-service:/app
    depends_on:
      - rabbitmq

volumes:
  postgres-data:
